#server:
#  port: 15003
#  servlet:
#    context-path: /api/${spring.application.name}
#download:
#  type: web
#upload:
#  file:
#    path: /upload/file/dir
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  health:
#    db:
#      enabled: true
#  endpoint:
#    health:
#      show-details: always
#spring:
#  jpa:
#    open-in-view: false
#  liquibase:
#    change-log: classpath:db/master.xml
#    default-schema: file-server
#  datasource:
#    url: jdbc:mysql://192.168.199.209:3307/file-server?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 111111
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      allow-pool-suspension: true
#      connection-test-query: 'select 1'
#      auto-commit: false
#      maximum-pool-size: 100
#      minimum-idle: 10
#      idle-timeout: 60000
#      max-lifetime: 600000
#      connection-timeout: 60000
#      validation-timeout: 60000
#      leak-detection-threshold: 60000
#  servlet:
#    multipart:
#      max-request-size: 3GB
#      max-file-size: 2GB
